<?php

use Illuminate\Database\Seeder;

class PostsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('posts')->insert([
            [
                'user_id' => '1',
                'area_id' => '3',
                'pref' => '11',
                'category_id' => '2',
                'dest' => 'Kamogawa',
                'date' => '05DEC20',
                'comment' => 'クラゲ',
                'image' => 'IMG_5477.jpg',
            ],
            [
                'user_id' => '1',
                'area_id' => '3',
                'pref' => '11',
                'category_id' => '2',
                'dest' => 'Kamogawa',
                'date' => '05DEC20',
                'comment' => '白いるか',
                'image' => 'IMG_5479.jpg',
            ],
            [
                'user_id' => '1',
                'area_id' => '3',
                'pref' => '11',
                'category_id' => '2',
                'dest' => 'Kamogawa',
                'date' => '05DEC20',
                'comment' => 'シャチのショー',
                'image' => 'IMG_5489.jpg',
            ],
            [
                'user_id' => '1',
                'area_id' => '3',
                'pref' => '11',
                'category_id' => '2',
                'dest' => 'Kamogawa',
                'date' => '05DEC20',
                'comment' => 'ウミガメ',
                'image' => 'IMG_5492.jpg',
            ],
            [
                'user_id' => '1',
                'area_id' => '3',
                'pref' => '11',
                'category_id' => '2',
                'dest' => 'Kamogawa',
                'date' => '05DEC20',
                'comment' => '隠れクマノミ',
                'image' => 'IMG_5496.jpg',
            ],
            [
                'user_id' => '1',
                'area_id' => '1',
                'pref' => '1',
                'category_id' => '1',
                'dest' => 'Sapporo',
                'date' => '26NOV18',
                'comment' => 'NIKKA',
                'image' => 'DSC02649_Original.jpg',
            ],
            [
                'user_id' => '1',
                'area_id' => '1',
                'pref' => '1',
                'category_id' => '3',
                'dest' => 'Sapporo',
                'date' => '26NOV18',
                'comment' => 'ドイツ祭り',
                'image' => 'DSC02655_Original.jpg',
            ],
            [
                'user_id' => '1',
                'area_id' => '1',
                'pref' => '1',
                'category_id' => '4',
                'dest' => 'Sapporo',
                'date' => '26NOV18',
                'comment' => 'ビールとウインナー',
                'image' => 'DSC02663_Original.jpg',
            ],
            [
                'user_id' => '1',
                'area_id' => '1',
                'pref' => '1',
                'category_id' => '3',
                'dest' => 'Sapporo',
                'date' => '26NOV18',
                'comment' => 'ビール工場',
                'image' => 'DSC02744_Original.jpg',
            ],
            [
                'user_id' => '1',
                'area_id' => '1',
                'pref' => '1',
                'category_id' => '1',
                'dest' => 'Sapporo',
                'date' => '26NOV18',
                'comment' => '小樽',
                'image' => 'DSC02769_Original.jpg',
            ],
            [
                'user_id' => '1',
                'area_id' => '6',
                'pref' => '33',
                'category_id' => '3',
                'dest' => 'Izumo',
                'date' => '14MAR22',
                'comment' => '出雲大社',
                'image' => '1C92AACF-6D11-492A-AD24-A00C7CB52D0E.JPEG',
            ],
            [
                'user_id' => '1',
                'area_id' => '6',
                'pref' => '33',
                'category_id' => '5',
                'dest' => 'Izumo',
                'date' => '14MAR22',
                'comment' => 'みんなでお守り',
                'image' => '7B33567E-8C57-4D7D-B1E3-F00F1935B5F5.JPEG',
            ],
            [
                'user_id' => '1',
                'area_id' => '6',
                'pref' => '33',
                'category_id' => '3',
                'dest' => 'Izumo',
                'date' => '14MAR22',
                'comment' => '大通り',
                'image' => '53703C0C-0253-40AD-B7BF-22CF91B11A94 (1).jpeg',
            ],
            [
                'user_id' => '1',
                'area_id' => '6',
                'pref' => '33',
                'category_id' => '2',
                'dest' => 'Izumo',
                'date' => '14MAR22',
                'comment' => '桜',
                'image' => 'B7734E1E-0DC9-4FF7-B076-776B1AE371C9.JPEG',
            ],
            [
                'user_id' => '1',
                'area_id' => '6',
                'pref' => '33',
                'category_id' => '4',
                'dest' => 'Izumo',
                'date' => '14MAR22',
                'comment' => '福乃和',
                'image' => 'D9E4FEB8-775A-4DB4-9F65-149BFBEFAA39.JPEG',
            ],
            [
                'user_id' => '1',
                'area_id' => '12',
                'pref' => '0',
                'category_id' => '1',
                'dest' => 'Vancouver',
                'date' => '08NOV13',
                'comment' => 'ちびっこのアイスホッケー',
                'image' => 'PB100083.jpg',
            ],
            [
                'user_id' => '1',
                'area_id' => '12',
                'pref' => '0',
                'category_id' => '2',
                'dest' => 'Vancouver',
                'date' => '08NOV13',
                'comment' => 'スタンレー・パーク',
                'image' => 'PB120148.jpg',
            ],
            [
                'user_id' => '1',
                'area_id' => '12',
                'pref' => '0',
                'category_id' => '1',
                'dest' => 'Vancouver',
                'date' => '08NOV13',
                'comment' => 'ギャスタウン',
                'image' => 'PB110129.jpg',
            ],
            [
                'user_id' => '1',
                'area_id' => '12',
                'pref' => '0',
                'category_id' => '1',
                'dest' => 'Vancouver',
                'date' => '08NOV13',
                'comment' => '聖火台',
                'image' => 'PB110102.jpg',
            ],
            [
                'user_id' => '1',
                'area_id' => '12',
                'pref' => '0',
                'category_id' => '1',
                'dest' => 'Vancouver',
                'date' => '08NOV13',
                'comment' => '蒸気時計',
                'image' => 'PB110131.jpg',
            ],
            [
                'user_id' => '1',
                'area_id' => '9',
                'pref' => '47',
                'category_id' => '4',
                'dest' => 'Ishigaki',
                'date' => '08NOV20',
                'comment' => '沖縄そば',
                'image' => 'IMG_5322.JPG',
            ],
            [
                'user_id' => '1',
                'area_id' => '9',
                'pref' => '47',
                'category_id' => '2',
                'dest' => 'Ishigaki',
                'date' => '08NOV20',
                'comment' => 'エメラルドグリーン',
                'image' => 'IMG_5335.JPG',
            ],
            [
                'user_id' => '1',
                'area_id' => '9',
                'pref' => '47',
                'category_id' => '2',
                'dest' => 'Ishigaki',
                'date' => '08NOV20',
                'comment' => '砂浜',
                'image' => 'IMG_5354.JPG',
            ],
            [
                'user_id' => '1',
                'area_id' => '9',
                'pref' => '47',
                'category_id' => '4',
                'dest' => 'Ishigaki',
                'date' => '08NOV20',
                'comment' => 'ゴーヤチャンプルー',
                'image' => 'IMG_5384.JPG',
            ],
            [
                'user_id' => '1',
                'area_id' => '9',
                'pref' => '47',
                'category_id' => '2',
                'dest' => 'Ishigaki',
                'date' => '08NOV20',
                'comment' => 'にんじんしりしり',
                'image' => 'IMG_5385.JPG',
            ],[
                'user_id' => '2',
                'area_id' => '2',
                'pref' => '6',
                'category_id' => '3',
                'dest' => 'Yamagata',
                'date' => '21NOV21',
                'comment' => '鳥海山大物忌神社',
                'image' => 'IMG_7162.jpg',
            ],[
                'user_id' => '2',
                'area_id' => '2',
                'pref' => '6',
                'category_id' => '2',
                'dest' => 'Yamagata',
                'date' => '21NOV21',
                'comment' => '紅葉',
                'image' => 'IMG_7167.jpg',
            ],[
                'user_id' => '2',
                'area_id' => '2',
                'pref' => '6',
                'category_id' => '2',
                'dest' => 'Yamagata',
                'date' => '21NOV21',
                'comment' => '牛渡川',
                'image' => 'IMG_7175.jpg',
            ],[
                'user_id' => '2',
                'area_id' => '2',
                'pref' => '6',
                'category_id' => '2',
                'dest' => 'Yamagata',
                'date' => '21NOV21',
                'comment' => '丸池様',
                'image' => 'IMG_7185.jpg',
            ],[
                'user_id' => '2',
                'area_id' => '2',
                'pref' => '6',
                'category_id' => '4',
                'dest' => 'Yamagata',
                'date' => '21NOV21',
                'comment' => '夕ご飯',
                'image' => 'IMG_7216.jpg',
            ],[
                'user_id' => '2',
                'area_id' => '3',
                'pref' => '9',
                'category_id' => '1',
                'dest' => 'Nasu',
                'date' => '14JUL20',
                'comment' => '那須ガーデンアウトレット',
                'image' => 'IMG_4653.JPG',
            ],[
                'user_id' => '2',
                'area_id' => '3',
                'pref' => '9',
                'category_id' => '4',
                'dest' => 'Nasu',
                'date' => '14JUL20',
                'comment' => 'ジンギスカン',
                'image' => 'IMG_4655.JPG',
            ],[
                'user_id' => '2',
                'area_id' => '3',
                'pref' => '9',
                'category_id' => '2',
                'dest' => 'Nasu',
                'date' => '14JUL20',
                'comment' => '南ヶ丘牧場',
                'image' => 'IMG_4657.JPG',
            ],[
                'user_id' => '2',
                'area_id' => '3',
                'pref' => '9',
                'category_id' => '4',
                'dest' => 'Nasu',
                'date' => '14JUL20',
                'comment' => 'ソフトクリーム',
                'image' => 'IMG_4661.JPG',
            ],[
                'user_id' => '2',
                'area_id' => '3',
                'pref' => '9',
                'category_id' => '3',
                'dest' => 'Nasu',
                'date' => '14JUL20',
                'comment' => '那須ハイランドパーク',
                'image' => 'IMG_4662.JPG',
            ],[
                'user_id' => '2',
                'area_id' => '4',
                'pref' => '20',
                'category_id' => '2',
                'dest' => 'Kanazawa',
                'date' => '13SEP18',
                'comment' => '兼六園',
                'image' => 'DSC02449_Original.jpg',
            ],[
                'user_id' => '2',
                'area_id' => '4',
                'pref' => '20',
                'category_id' => '4',
                'dest' => 'Kanazawa',
                'date' => '13SEP18',
                'comment' => '金箔ソフト',
                'image' => 'IMG_1027_Original.jpg',
            ],[
                'user_id' => '2',
                'area_id' => '4',
                'pref' => '20',
                'category_id' => '3',
                'dest' => 'Kanazawa',
                'date' => '13SEP18',
                'comment' => 'ひがし茶屋街',
                'image' => 'IMG_1041_Original.jpg',
            ],[
                'user_id' => '2',
                'area_id' => '4',
                'pref' => '20',
                'category_id' => '4',
                'dest' => 'Kanazawa',
                'date' => '13SEP18',
                'comment' => '金沢駅',
                'image' => 'IMG_1015_Original.jpg',
            ],[
                'user_id' => '2',
                'area_id' => '4',
                'pref' => '20',
                'category_id' => '4',
                'dest' => 'Kanazawa',
                'date' => '13SEP18',
                'comment' => '輪島プリン',
                'image' => 'IMG_1066_Original.jpg',
            ],[
                'user_id' => '2',
                'area_id' => '7',
                'pref' => '36',
                'category_id' => '5',
                'dest' => 'Kagawa',
                'date' => '01NOV20',
                'comment' => 'ANKの飛行機',
                'image' => 'IMG_5160.jpg',
            ],[
                'user_id' => '2',
                'area_id' => '7',
                'pref' => '36',
                'category_id' => '5',
                'dest' => 'Kagawa',
                'date' => '01NOV20',
                'comment' => 'コックピット',
                'image' => 'IMG_5170.jpg',
            ],[
                'user_id' => '2',
                'area_id' => '7',
                'pref' => '36',
                'category_id' => '2',
                'dest' => 'Kagawa',
                'date' => '01NOV20',
                'comment' => 'さぬきこどもの国',
                'image' => 'IMG_5176.jpg',
            ],[
                'user_id' => '2',
                'area_id' => '7',
                'pref' => '36',
                'category_id' => '4',
                'dest' => 'Kagawa',
                'date' => '01NOV20',
                'comment' => '瀬戸晴れ',
                'image' => 'IMG_5185.jpg',
            ],[
                'user_id' => '2',
                'area_id' => '7',
                'pref' => '36',
                'category_id' => '4',
                'dest' => 'Kagawa',
                'date' => '01NOV20',
                'comment' => 'うどん',
                'image' => 'IMG_5199.jpg',
            ],[
                'user_id' => '2',
                'area_id' => '11',
                'pref' => '0',
                'category_id' => '2',
                'dest' => 'Malaysia',
                'date' => '17MAY15',
                'comment' => '大学からの夕焼け',
                'image' => 'IMG_3113_Original.jpg',
            ],[
                'user_id' => '2',
                'area_id' => '11',
                'pref' => '0',
                'category_id' => '3',
                'dest' => 'Malaysia',
                'date' => '17MAY15',
                'comment' => '学生のダンス',
                'image' => 'IMG_1785_Original.jpg',
            ],[
                'user_id' => '2',
                'area_id' => '11',
                'pref' => '0',
                'category_id' => '1',
                'dest' => 'Malaysia',
                'date' => '17MAY15',
                'comment' => 'カンパー市内',
                'image' => 'IMG_1288_Original.jpg',
            ],[
                'user_id' => '2',
                'area_id' => '11',
                'pref' => '0',
                'category_id' => '3',
                'dest' => 'Malaysia',
                'date' => '17MAY15',
                'comment' => '飛行機',
                'image' => 'IMG_3357_Original.jpg',
            ],[
                'user_id' => '2',
                'area_id' => '11',
                'pref' => '0',
                'category_id' => '3',
                'dest' => 'Malaysia',
                'date' => '17MAY15',
                'comment' => 'カンパーの遺跡',
                'image' => 'IMG_3360_Original.jpg',
            ],[
                'user_id' => '3',
                'area_id' => '3',
                'pref' => '8',
                'category_id' => '1',
                'dest' => 'Kashima',
                'date' => '26MAY21',
                'comment' => '鹿島スタジアム',
                'image' => 'IMG_6233.JPG',
            ],[
                'user_id' => '3',
                'area_id' => '3',
                'pref' => '8',
                'category_id' => '4',
                'dest' => 'Kashima',
                'date' => '26MAY21',
                'comment' => 'ビール最高！',
                'image' => 'IMG_6236.JPG',
            ],[
                'user_id' => '3',
                'area_id' => '3',
                'pref' => '8',
                'category_id' => '5',
                'dest' => 'Kashima',
                'date' => '26MAY21',
                'comment' => '初サッカー観戦',
                'image' => 'IMG_6238.JPG',
            ],[
                'user_id' => '3',
                'area_id' => '3',
                'pref' => '8',
                'category_id' => '5',
                'dest' => 'Kashima',
                'date' => '26MAY21',
                'comment' => '楽しみ！',
                'image' => 'IMG_6242.JPG',
            ],[
                'user_id' => '3',
                'area_id' => '3',
                'pref' => '8',
                'category_id' => '5',
                'dest' => 'Kashima',
                'date' => '26MAY21',
                'comment' => 'キックオフ',
                'image' => 'IMG_6246.JPG',
            ],[
                'user_id' => '3',
                'area_id' => '3',
                'pref' => '14',
                'category_id' => '2',
                'dest' => 'Sarujima',
                'date' => '19SEP19',
                'comment' => '横須賀湾',
                'image' => 'IMG_3418_Original.jpg',
            ],[
                'user_id' => '3',
                'area_id' => '3',
                'pref' => '14',
                'category_id' => '2',
                'dest' => 'Sarujima',
                'date' => '19SEP19',
                'comment' => '猿島到着！',
                'image' => 'IMG_3431_Original.jpg',
            ],[
                'user_id' => '3',
                'area_id' => '3',
                'pref' => '14',
                'category_id' => '2',
                'dest' => 'Sarujima',
                'date' => '19SEP19',
                'comment' => '猿島島内',
                'image' => 'IMG_3420_Original.jpg',
            ],[
                'user_id' => '3',
                'area_id' => '3',
                'pref' => '14',
                'category_id' => '2',
                'dest' => 'Sarujima',
                'date' => '19SEP19',
                'comment' => '不思議な雰囲気',
                'image' => 'IMG_3422_Original.jpg',
            ],[
                'user_id' => '3',
                'area_id' => '3',
                'pref' => '14',
                'category_id' => '2',
                'dest' => 'Sarujima',
                'date' => '19SEP19',
                'comment' => 'トンネル',
                'image' => 'IMG_3425_Original.jpg',
            ],[
                'user_id' => '3',
                'area_id' => '5',
                'pref' => '26',
                'category_id' => '3',
                'dest' => 'Kyoto',
                'date' => '08AUG18',
                'comment' => '平等院鳳凰堂',
                'image' => 'DSC01957_Original.jpg',
            ],[
                'user_id' => '3',
                'area_id' => '5',
                'pref' => '26',
                'category_id' => '3',
                'dest' => 'Kyoto',
                'date' => '08AUG18',
                'comment' => '平等院正面',
                'image' => 'DSC01986_Original.jpg',
            ],[
                'user_id' => '3',
                'area_id' => '5',
                'pref' => '26',
                'category_id' => '4',
                'dest' => 'Kyoto',
                'date' => '08AUG18',
                'comment' => 'スタバ平等院表参道店',
                'image' => 'DSC01990_Original.jpg',
            ],[
                'user_id' => '3',
                'area_id' => '5',
                'pref' => '26',
                'category_id' => '4',
                'dest' => 'Kyoto',
                'date' => '08AUG18',
                'comment' => '抹茶餃子',
                'image' => 'DSC02001_Original.jpg',
            ],[
                'user_id' => '3',
                'area_id' => '5',
                'pref' => '26',
                'category_id' => '3',
                'dest' => 'Kyoto',
                'date' => '08AUG18',
                'comment' => '伏見稲荷の夕焼け',
                'image' => 'DSC02027_Original.jpg',
            ],[
                'user_id' => '3',
                'area_id' => '6',
                'pref' => '34',
                'category_id' => '5',
                'dest' => 'Hiroshima',
                'date' => '23NOV19',
                'comment' => '出発！',
                'image' => 'IMG_3594_Original.jpg',
            ],[
                'user_id' => '3',
                'area_id' => '6',
                'pref' => '34',
                'category_id' => '2',
                'dest' => 'Hiroshima',
                'date' => '23NOV19',
                'comment' => '厳島へ',
                'image' => 'DSC03112_Original.jpg',
            ],[
                'user_id' => '3',
                'area_id' => '6',
                'pref' => '34',
                'category_id' => '3',
                'dest' => 'Hiroshima',
                'date' => '23NOV19',
                'comment' => '工事中。。笑',
                'image' => 'DSC03117_Original.jpg',
            ],[
                'user_id' => '3',
                'area_id' => '6',
                'pref' => '34',
                'category_id' => '3',
                'dest' => 'Hiroshima',
                'date' => '23NOV19',
                'comment' => '厳島島内',
                'image' => 'DSC03115_Original.jpg',
            ],[
                'user_id' => '3',
                'area_id' => '6',
                'pref' => '34',
                'category_id' => '3',
                'dest' => 'Hiroshima',
                'date' => '23NOV19',
                'comment' => '厳島神社',
                'image' => 'DSC03124_Original.jpg',
            ],[
                'user_id' => '3',
                'area_id' => '11',
                'pref' => '0',
                'category_id' => '4',
                'dest' => 'Korea',
                'date' => '19FEB19',
                'comment' => 'マフィン',
                'image' => 'IMG_2329_Original.jpg',
            ],[
                'user_id' => '3',
                'area_id' => '11',
                'pref' => '0',
                'category_id' => '5',
                'dest' => 'Korea',
                'date' => '19FEB19',
                'comment' => 'にゃんこ〜',
                'image' => 'IMG_2331_Original.jpg',
            ],[
                'user_id' => '3',
                'area_id' => '11',
                'pref' => '0',
                'category_id' => '1',
                'dest' => 'Korea',
                'date' => '19FEB19',
                'comment' => '悟った椅子',
                'image' => 'IMG_2334_Original.jpg',
            ],[
                'user_id' => '3',
                'area_id' => '11',
                'pref' => '0',
                'category_id' => '1',
                'dest' => 'Korea',
                'date' => '19FEB19',
                'comment' => '唯一の韓国語スタバ',
                'image' => 'IMG_2337_Original.jpg',
            ],[
                'user_id' => '3',
                'area_id' => '11',
                'pref' => '0',
                'category_id' => '4',
                'dest' => 'Korea',
                'date' => '19FEB19',
                'comment' => 'キムチ',
                'image' => 'IMG_2338_Original.jpg',
            ],[
                'user_id' => '4',
                'area_id' => '1',
                'pref' => '1',
                'category_id' => '4',
                'dest' => 'Sapporo',
                'date' => '26NOV18',
                'comment' => '鮭といくらの親子丼',
                'image' => 'DSC02709_Original.jpg',
            ],[
                'user_id' => '4',
                'area_id' => '1',
                'pref' => '1',
                'category_id' => '3',
                'dest' => 'Sapporo',
                'date' => '26NOV18',
                'comment' => 'クラーク博士',
                'image' => 'DSC02789_Original.jpg',
            ],[
                'user_id' => '4',
                'area_id' => '1',
                'pref' => '1',
                'category_id' => '2',
                'dest' => 'Sapporo',
                'date' => '26NOV18',
                'comment' => '支笏湖',
                'image' => 'DSC02802_Original.jpg',
            ],[
                'user_id' => '4',
                'area_id' => '1',
                'pref' => '1',
                'category_id' => '2',
                'dest' => 'Sapporo',
                'date' => '26NOV18',
                'comment' => '冒険の匂い。。',
                'image' => 'DSC02819_Original.jpg',
            ],[
                'user_id' => '4',
                'area_id' => '1',
                'pref' => '1',
                'category_id' => '4',
                'dest' => 'Sapporo',
                'date' => '26NOV18',
                'comment' => 'トリトン',
                'image' => 'IMG_1826_Original.jpg',
            ],[
                'user_id' => '4',
                'area_id' => '4',
                'pref' => '17',
                'category_id' => '2',
                'dest' => 'Yamanashi',
                'date' => '05NOV18',
                'comment' => '鳴沢氷穴',
                'image' => 'DSC02549_Original.jpg',
            ],[
                'user_id' => '4',
                'area_id' => '4',
                'pref' => '17',
                'category_id' => '2',
                'dest' => 'Yamanashi',
                'date' => '05NOV18',
                'comment' => '鳴沢氷穴入口',
                'image' => 'DSC02564_Original.jpg',
            ],[
                'user_id' => '4',
                'area_id' => '4',
                'pref' => '17',
                'category_id' => '2',
                'dest' => 'Yamanashi',
                'date' => '05NOV18',
                'comment' => '紅葉＠河口湖',
                'image' => 'DSC02597_Original.jpg',
            ],[
                'user_id' => '4',
                'area_id' => '4',
                'pref' => '17',
                'category_id' => '4',
                'dest' => 'Yamanashi',
                'date' => '05NOV18',
                'comment' => '夕食',
                'image' => 'DSC02625_Original.jpg',
            ],[
                'user_id' => '4',
                'area_id' => '4',
                'pref' => '17',
                'category_id' => '4',
                'dest' => 'Yamanashi',
                'date' => '05NOV18',
                'comment' => 'ソフトクリーム',
                'image' => 'IMG_1511_Original.jpg',
            ],[
                'user_id' => '4',
                'area_id' => '5',
                'pref' => '26',
                'category_id' => '3',
                'dest' => 'Kyoto',
                'date' => '09AUG18',
                'comment' => '清水寺',
                'image' => 'DSC02138_Original.jpg',
            ],[
                'user_id' => '4',
                'area_id' => '5',
                'pref' => '26',
                'category_id' => '3',
                'dest' => 'Kyoto',
                'date' => '09AUG18',
                'comment' => '仁王門',
                'image' => 'DSC02149_Original.jpg',
            ],[
                'user_id' => '4',
                'area_id' => '5',
                'pref' => '26',
                'category_id' => '3',
                'dest' => 'Kyoto',
                'date' => '09AUG18',
                'comment' => '二年坂',
                'image' => 'DSC02153_Original.jpg',
            ],[
                'user_id' => '4',
                'area_id' => '5',
                'pref' => '26',
                'category_id' => '3',
                'dest' => 'Kyoto',
                'date' => '09AUG18',
                'comment' => '法観寺',
                'image' => 'DSC02162_Original.jpg',
            ],[
                'user_id' => '4',
                'area_id' => '5',
                'pref' => '26',
                'category_id' => '3',
                'dest' => 'Kyoto',
                'date' => '09AUG18',
                'comment' => '平安神宮',
                'image' => 'DSC02193_Original.jpg',
            ],[
                'user_id' => '4',
                'area_id' => '6',
                'pref' => '33',
                'category_id' => '3',
                'dest' => 'Izumo',
                'date' => '14MAR22',
                'comment' => '正門',
                'image' => 'A3C0AFE6-F9EE-4968-AEA4-A91E7F668E66.JPEG',
            ],[
                'user_id' => '4',
                'area_id' => '6',
                'pref' => '33',
                'category_id' => '3',
                'dest' => 'Izumo',
                'date' => '14MAR22',
                'comment' => '弁天島＠稲佐の浜',
                'image' => 'A72B117D-C981-4FAD-9E8E-1E9AA4B4A2CD.JPEG',
            ],[
                'user_id' => '4',
                'area_id' => '6',
                'pref' => '33',
                'category_id' => '5',
                'dest' => 'Izumo',
                'date' => '14MAR22',
                'comment' => '出雲大社',
                'image' => 'IMG_7884.jpg',
            ],[
                'user_id' => '4',
                'area_id' => '6',
                'pref' => '33',
                'category_id' => '4',
                'dest' => 'Izumo',
                'date' => '14MAR22',
                'comment' => 'スタバ出雲大社店',
                'image' => 'IMG_7897.jpg',
            ],[
                'user_id' => '4',
                'area_id' => '6',
                'pref' => '33',
                'category_id' => '4',
                'dest' => 'Izumo',
                'date' => '14MAR22',
                'comment' => '海鮮丼',
                'image' => 'IMG_7903.jpg',
            ],[
                'user_id' => '4',
                'area_id' => '11',
                'pref' => '0',
                'category_id' => '3',
                'dest' => 'Malaysia',
                'date' => '11MAR16',
                'comment' => 'ペナン市内',
                'image' => 'IMG_5566_Original.jpg',
            ],[
                'user_id' => '4',
                'area_id' => '11',
                'pref' => '0',
                'category_id' => '2',
                'dest' => 'Malaysia',
                'date' => '11MAR16',
                'comment' => 'ロープウェイから',
                'image' => 'IMG_5574_Original.jpg',
            ],[
                'user_id' => '4',
                'area_id' => '11',
                'pref' => '0',
                'category_id' => '2',
                'dest' => 'Malaysia',
                'date' => '11MAR16',
                'comment' => 'ランカウィの夕焼け',
                'image' => 'IMG_5594_Original_Original.jpg',
            ],[
                'user_id' => '4',
                'area_id' => '11',
                'pref' => '0',
                'category_id' => '2',
                'dest' => 'Malaysia',
                'date' => '11MAR16',
                'comment' => 'アイランドホッピング',
                'image' => 'IMG_5613_Original.jpg',
            ],[
                'user_id' => '4',
                'area_id' => '11',
                'pref' => '0',
                'category_id' => '3',
                'dest' => 'Malaysia',
                'date' => '11MAR16',
                'comment' => '鷹？の像',
                'image' => 'IMG_5631_Original.jpg',
            ],[
                'user_id' => '5',
                'area_id' => '4',
                'pref' => '16',
                'category_id' => '3',
                'dest' => 'Nagano',
                'date' => '03AUG21',
                'comment' => '善光寺',
                'image' => 'IMG_6655.jpg',
            ],[
                'user_id' => '5',
                'area_id' => '4',
                'pref' => '16',
                'category_id' => '4',
                'dest' => 'Nagano',
                'date' => '03AUG21',
                'comment' => '甘味処鎌倉抹茶',
                'image' => 'IMG_6657.jpg',
            ],[
                'user_id' => '5',
                'area_id' => '4',
                'pref' => '16',
                'category_id' => '4',
                'dest' => 'Nagano',
                'date' => '03AUG21',
                'comment' => '味噌おにぎり',
                'image' => 'IMG_6665.jpg',
            ],[
                'user_id' => '5',
                'area_id' => '4',
                'pref' => '16',
                'category_id' => '4',
                'dest' => 'Nagano',
                'date' => '03AUG21',
                'comment' => 'スタバ善光寺店',
                'image' => 'IMG_6661.jpg',
            ],[
                'user_id' => '5',
                'area_id' => '4',
                'pref' => '16',
                'category_id' => '3',
                'dest' => 'Nagano',
                'date' => '03AUG21',
                'comment' => '長野駅',
                'image' => 'IMG_6667.jpg',
            ],[
                'user_id' => '5',
                'area_id' => '5',
                'pref' => '29',
                'category_id' => '4',
                'dest' => 'Kobe',
                'date' => '20OCT21',
                'comment' => 'スタバ北野偉人館店',
                'image' => 'IMG_6938.JPG',
            ],[
                'user_id' => '5',
                'area_id' => '5',
                'pref' => '29',
                'category_id' => '3',
                'dest' => 'Kobe',
                'date' => '20OCT21',
                'comment' => '北野偉人館',
                'image' => 'IMG_6943.jpg',
            ],[
                'user_id' => '5',
                'area_id' => '5',
                'pref' => '29',
                'category_id' => '3',
                'dest' => 'Kobe',
                'date' => '20OCT21',
                'comment' => 'ホームズグッズ',
                'image' => 'IMG_6949.jpg',
            ],[
                'user_id' => '5',
                'area_id' => '5',
                'pref' => '29',
                'category_id' => '3',
                'dest' => 'Kobe',
                'date' => '20OCT21',
                'comment' => 'ベイカーストリート駅',
                'image' => 'IMG_6960.jpg',
            ],[
                'user_id' => '5',
                'area_id' => '5',
                'pref' => '29',
                'category_id' => '3',
                'dest' => 'Kobe',
                'date' => '20OCT21',
                'comment' => '偉人館内',
                'image' => 'IMG_6973.jpg',
            ],[
                'user_id' => '5',
                'area_id' => '6',
                'pref' => '34',
                'category_id' => '3',
                'dest' => 'Hiroshima',
                'date' => '24NOV19',
                'comment' => '原爆ドーム',
                'image' => 'DSC03137_Original.jpg',
            ],[
                'user_id' => '5',
                'area_id' => '6',
                'pref' => '34',
                'category_id' => '3',
                'dest' => 'Hiroshima',
                'date' => '24NOV19',
                'comment' => '原爆ドーム内部',
                'image' => 'DSC03139_Original.jpg',
            ],[
                'user_id' => '5',
                'area_id' => '6',
                'pref' => '34',
                'category_id' => '3',
                'dest' => 'Hiroshima',
                'date' => '24NOV19',
                'comment' => '広島城×紅葉',
                'image' => 'DSC03143_Original.jpg',
            ],[
                'user_id' => '5',
                'area_id' => '6',
                'pref' => '34',
                'category_id' => '3',
                'dest' => 'Hiroshima',
                'date' => '24NOV19',
                'comment' => '広島城',
                'image' => 'DSC03146_Original.jpg',
            ],[
                'user_id' => '5',
                'area_id' => '6',
                'pref' => '34',
                'category_id' => '1',
                'dest' => 'Hiroshima',
                'date' => '24NOV19',
                'comment' => '路面電車',
                'image' => 'IMG_3611_Original.jpg',
            ],[
                'user_id' => '5',
                'area_id' => '9',
                'pref' => '47',
                'category_id' => '2',
                'dest' => 'Ishigaki',
                'date' => '08NOV20',
                'comment' => '到着！',
                'image' => 'IMG_5318.jpg',
            ],[
                'user_id' => '5',
                'area_id' => '9',
                'pref' => '47',
                'category_id' => '4',
                'dest' => 'Ishigaki',
                'date' => '08NOV20',
                'comment' => '嶋そば一番地',
                'image' => 'IMG_5325.JPG',
            ],[
                'user_id' => '5',
                'area_id' => '9',
                'pref' => '47',
                'category_id' => '4',
                'dest' => 'Ishigaki',
                'date' => '08NOV20',
                'comment' => 'Mマリヤシェイク',
                'image' => 'IMG_5340.JPG',
            ],[
                'user_id' => '5',
                'area_id' => '9',
                'pref' => '47',
                'category_id' => '4',
                'dest' => 'Ishigaki',
                'date' => '08NOV20',
                'comment' => '締めのスイーツ',
                'image' => 'IMG_5392.JPG',
            ],[
                'user_id' => '5',
                'area_id' => '9',
                'pref' => '47',
                'category_id' => '2',
                'dest' => 'Ishigaki',
                'date' => '08NOV20',
                'comment' => '花火',
                'image' => 'IMG_5396.jpg',
            ],[
                'user_id' => '5',
                'area_id' => '11',
                'pref' => '0',
                'category_id' => '5',
                'dest' => 'Korea',
                'date' => '19FEB19',
                'comment' => '出発！',
                'image' => 'IMG_2250_Original.jpg',
            ],[
                'user_id' => '5',
                'area_id' => '11',
                'pref' => '0',
                'category_id' => '5',
                'dest' => 'Korea',
                'date' => '19FEB19',
                'comment' => '到着！',
                'image' => 'IMG_2256_Original.jpg',
            ],[
                'user_id' => '5',
                'area_id' => '11',
                'pref' => '0',
                'category_id' => '1',
                'dest' => 'Korea',
                'date' => '19FEB19',
                'comment' => '繁華街',
                'image' => 'IMG_2261_Original.jpg',
            ],[
                'user_id' => '5',
                'area_id' => '11',
                'pref' => '0',
                'category_id' => '5',
                'dest' => 'Korea',
                'date' => '19FEB19',
                'comment' => '合流！',
                'image' => 'IMG_2264_Original.jpg',
            ],[
                'user_id' => '5',
                'area_id' => '11',
                'pref' => '0',
                'category_id' => '4',
                'dest' => 'Korea',
                'date' => '19FEB19',
                'comment' => '本場のチーズタッカルビ',
                'image' => 'IMG_2266_Original.jpg',
            ],
        ]);
    }
}
