<?php

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('posts')->insert([
            [
                'user_id' => '3',
                'area_id' => '3',
                'pref' => '11',
                'category_id' => '2',
                'dest' => 'Kamogawa',
                'date' => '05DEC20',
                'comment' => 'クラゲ',
                'image' => 'IMG_5477.jpg',
            ],
            [
                'user_id' => '3',
                'area_id' => '3',
                'pref' => '11',
                'category_id' => '2',
                'dest' => 'Kamogawa',
                'date' => '05DEC20',
                'comment' => '白いるか',
                'image' => 'IMG_5479.jpg',
            ],
            [
                'user_id' => '3',
                'area_id' => '3',
                'pref' => '11',
                'category_id' => '2',
                'dest' => 'Kamogawa',
                'date' => '05DEC20',
                'comment' => 'シャチのショー',
                'image' => 'IMG_5489.jpg',
            ],
            [
                'user_id' => '3',
                'area_id' => '3',
                'pref' => '11',
                'category_id' => '2',
                'dest' => 'Kamogawa',
                'date' => '05DEC20',
                'comment' => 'ウミガメ',
                'image' => 'IMG_5492.jpg',
            ],
            [
                'user_id' => '3',
                'area_id' => '3',
                'pref' => '11',
                'category_id' => '2',
                'dest' => 'Kamogawa',
                'date' => '05DEC20',
                'comment' => '隠れクマノミ',
                'image' => 'IMG_5496.jpg',
            ],
            [
                'user_id' => '3',
                'area_id' => '1',
                'pref' => '1',
                'category_id' => '1',
                'dest' => 'Sapporo',
                'date' => '26NOV18',
                'comment' => 'NIKKA',
                'image' => 'DSC02649_Original.jpg',
            ],
            [
                'user_id' => '3',
                'area_id' => '1',
                'pref' => '1',
                'category_id' => '3',
                'dest' => 'Sapporo',
                'date' => '26NOV18',
                'comment' => 'ドイツ祭り',
                'image' => 'DSC02655_Original.jpg',
            ],
            [
                'user_id' => '3',
                'area_id' => '1',
                'pref' => '1',
                'category_id' => '4',
                'dest' => 'Sapporo',
                'date' => '26NOV18',
                'comment' => 'ビールとウインナー',
                'image' => 'DSC02663_Original.jpg',
            ],
            [
                'user_id' => '3',
                'area_id' => '1',
                'pref' => '1',
                'category_id' => '3',
                'dest' => 'Sapporo',
                'date' => '26NOV18',
                'comment' => 'ビール工場',
                'image' => 'DSC02744_Original.jpg',
            ],
            [
                'user_id' => '3',
                'area_id' => '1',
                'pref' => '1',
                'category_id' => '1',
                'dest' => 'Sapporo',
                'date' => '26NOV18',
                'comment' => '小樽',
                'image' => 'DSC02769_Original.jpg',
            ],
            [
                'user_id' => '3',
                'area_id' => '6',
                'pref' => '33',
                'category_id' => '3',
                'dest' => 'Izumo',
                'date' => '14MAR22',
                'comment' => '出雲大社',
                'image' => '1C92AACF-6D11-492A-AD24-A00C7CB52D0E.JPEG',
            ],
            [
                'user_id' => '3',
                'area_id' => '6',
                'pref' => '33',
                'category_id' => '5',
                'dest' => 'Izumo',
                'date' => '14MAR22',
                'comment' => 'みんなでお守り',
                'image' => '7B33567E-8C57-4D7D-B1E3-F00F1935B5F5.JPEG',
            ],
            [
                'user_id' => '3',
                'area_id' => '6',
                'pref' => '33',
                'category_id' => '3',
                'dest' => 'Izumo',
                'date' => '14MAR22',
                'comment' => '大通り',
                'image' => '53703C0C-0253-40AD-B7BF-22CF91B11A94 (1).jpeg',
            ],
            [
                'user_id' => '3',
                'area_id' => '6',
                'pref' => '33',
                'category_id' => '2',
                'dest' => 'Izumo',
                'date' => '14MAR22',
                'comment' => '桜',
                'image' => 'B7734E1E-0DC9-4FF7-B076-776B1AE371C9.JPEG',
            ],
            [
                'user_id' => '3',
                'area_id' => '6',
                'pref' => '33',
                'category_id' => '4',
                'dest' => 'Izumo',
                'date' => '14MAR22',
                'comment' => '福乃和',
                'image' => 'D9E4FEB8-775A-4DB4-9F65-149BFBEFAA39.JPEG',
            ],
            [
                'user_id' => '3',
                'area_id' => '12',
                'pref' => '0',
                'category_id' => '1',
                'dest' => 'Vancouver',
                'date' => '08NOV13',
                'comment' => 'ちびっこのアイスホッケー',
                'image' => 'PB100083.jpg',
            ],
            [
                'user_id' => '3',
                'area_id' => '12',
                'pref' => '0',
                'category_id' => '2',
                'dest' => 'Vancouver',
                'date' => '08NOV13',
                'comment' => 'スタンレー・パーク',
                'image' => 'PB120148.jpg',
            ],
            [
                'user_id' => '3',
                'area_id' => '12',
                'pref' => '0',
                'category_id' => '1',
                'dest' => 'Vancouver',
                'date' => '08NOV13',
                'comment' => 'ギャスタウン',
                'image' => 'PB110129.jpg',
            ],
            [
                'user_id' => '3',
                'area_id' => '12',
                'pref' => '0',
                'category_id' => '1',
                'dest' => 'Vancouver',
                'date' => '08NOV13',
                'comment' => '聖火台',
                'image' => 'PB110102.jpg',
            ],
            [
                'user_id' => '3',
                'area_id' => '12',
                'pref' => '0',
                'category_id' => '1',
                'dest' => 'Vancouver',
                'date' => '08NOV13',
                'comment' => '蒸気時計',
                'image' => 'PB110131.jpg',
            ],
            [
                'user_id' => '3',
                'area_id' => '9',
                'pref' => '47',
                'category_id' => '4',
                'dest' => 'Ishigaki',
                'date' => '08NOV20',
                'comment' => '沖縄そば',
                'image' => 'IMG_5322.JPG',
            ],
            [
                'user_id' => '3',
                'area_id' => '9',
                'pref' => '47',
                'category_id' => '2',
                'dest' => 'Ishigaki',
                'date' => '08NOV20',
                'comment' => 'エメラルドグリーン',
                'image' => 'IMG_5335.JPG',
            ],
            [
                'user_id' => '3',
                'area_id' => '9',
                'pref' => '47',
                'category_id' => '2',
                'dest' => 'Ishigaki',
                'date' => '08NOV20',
                'comment' => '砂浜',
                'image' => 'IMG_5354.JPG',
            ],
            [
                'user_id' => '3',
                'area_id' => '9',
                'pref' => '47',
                'category_id' => '4',
                'dest' => 'Ishigaki',
                'date' => '08NOV20',
                'comment' => 'ゴーヤチャンプルー',
                'image' => 'IMG_5384.JPG',
            ],
            [
                'user_id' => '3',
                'area_id' => '9',
                'pref' => '47',
                'category_id' => '2',
                'dest' => 'Ishigaki',
                'date' => '08NOV20',
                'comment' => 'にんじんしりしり',
                'image' => 'IMG_5385.JPG',
            ],
        ]);
    }
}
